# NOTE: run bin/format-filters after changing this file
opal_filter "Exception" do
  fails "An Exception reaching the top level is printed on STDERR" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x830fa>
  fails "An Exception reaching the top level the Exception#cause is printed to STDERR with backtraces" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x830fa>
  fails "An Exception reaching the top level with a custom backtrace is printed on STDERR" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x830fa>
  fails "Errno::EAGAIN is the same class as Errno::EWOULDBLOCK if they represent the same errno value" # NameError: uninitialized constant Errno::EAGAIN
  fails "Errno::EINVAL.new accepts an optional custom message and location" # ArgumentError: [EINVAL.new] wrong number of arguments (given 2, expected -1)
  fails "Errno::EINVAL.new accepts an optional custom message" # Expected 22 == Errno to be truthy but was false
  fails "Errno::EINVAL.new can be called with no arguments" # Expected 22 == Errno to be truthy but was false
  fails "Errno::ENOTSUP is defined" # Expected Errno to have constant 'ENOTSUP' but it does not
  fails "Errno::ENOTSUP is the same class as Errno::EOPNOTSUPP if they represent the same errno value" # NameError: uninitialized constant Errno::ENOTSUP
  fails "Exception#== returns true if both exceptions have the same class, no message, and no backtrace" # Expected #<RuntimeError: RuntimeError> == #<RuntimeError: RuntimeError> to be truthy but was false
  fails "Exception#== returns true if both exceptions have the same class, the same message, and no backtrace" # Expected #<TypeError: message> == #<TypeError: message> to be truthy but was false
  fails "Exception#== returns true if both exceptions have the same class, the same message, and the same backtrace" # Expected #<TypeError: message> == #<TypeError: message> to be truthy but was false
  fails "Exception#== returns true if one exception is the dup'd copy of the other" # Expected #<ArgumentError: ArgumentError> == #<ArgumentError: ArgumentError> to be truthy but was false
  fails "Exception#== returns true if the two objects subclass Exception and have the same message and backtrace" # Expected #<ExceptionSpecs::UnExceptional: ExceptionSpecs::UnExceptional> == #<ExceptionSpecs::UnExceptional: ExceptionSpecs::UnExceptional> to be truthy but was false
  fails "Exception#backtrace captures the backtrace for an exception into $!" # Expected "<internal:corelib/kernel.rb>:609:37:in `raise'" =~ /backtrace_spec/ to be truthy but was nil
  fails "Exception#backtrace captures the backtrace for an exception into $@" # Expected "<internal:corelib/kernel.rb>:609:37:in `raise'" =~ /backtrace_spec/ to be truthy but was nil
  fails "Exception#backtrace includes the filename of the location immediately prior to where self raised in the second element" # Expected "ruby/core/exception/fixtures/common.rb:7:9:in `backtrace'" =~ /backtrace_spec\.rb/ to be truthy but was nil
  fails "Exception#backtrace includes the filename of the location where self raised in the first element" # Expected "<internal:corelib/kernel.rb>:609:37:in `raise'" =~ /common\.rb/ to be truthy but was nil
  fails "Exception#backtrace includes the line number of the location immediately prior to where self raised in the second element" # Expected "ruby/core/exception/fixtures/common.rb:7:9:in `backtrace'" =~ /:6(:in )?/ to be truthy but was nil
  fails "Exception#backtrace includes the line number of the location where self raised in the first element" # Expected "<internal:corelib/kernel.rb>:609:37:in `raise'" =~ /:7:in / to be truthy but was nil
  fails "Exception#backtrace includes the name of the method from where self raised in the first element" # Expected "<internal:corelib/kernel.rb>:609:37:in `raise'" =~ /in `backtrace'/ to be truthy but was nil
  fails "Exception#backtrace returns nil if no backtrace was set" # Expected ["ruby/core/exception/backtrace_spec.rb:10:14:in `instance_exec'", "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `instance_exec'", "mspec/runner/mspec.rb:116:11:in `protect'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `protect'", "mspec/runner/context.rb:176:39:in `$$17'", "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'", "<internal:corelib/enumerable.rb>:27:16:in `$$3'", "<internal:corelib/runtime.js>:1644:7:in `each'", "<internal:corelib/array.rb>:983:1:in `each'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each'", "<internal:corelib/enumerable.rb>:26:7:in `Enumerable_all$ques$1'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `all?'", "mspec/runner/context.rb:176:18:in `protect'", "mspec/runner/context.rb:212:26:in `$$21'", "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'", "mspec/runner/mspec.rb:284:7:in `repeat'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `repeat'", "mspec/runner/context.rb:204:16:in `$$20'", "<internal:corelib/runtime.js>:1644:7:in `each'", "<internal:corelib/array.rb>:983:1:in `each'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each'", "mspec/runner/context.rb:203:18:in `process'", "mspec/runner/mspec.rb:55:10:in `describe'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `describe'", "mspec/runner/object.rb:11:10:in `describe'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `describe'", "ruby/core/exception/backtrace_spec.rb:4:1:in `Opal.modules.ruby/core/exception/backtrace_spec'", "<internal:corelib/runtime.js>:2692:7:in `Opal.load_normalized'", "<internal:corelib/runtime.js>:2721:5:in `load'", "<internal:corelib/kernel.rb>:535:6:in `load'", "mspec/runner/mspec.rb:99:42:in `instance_exec'", "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `instance_exec'", "mspec/runner/mspec.rb:116:11:in `protect'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `protect'", "mspec/runner/mspec.rb:99:7:in `$$1'", "<internal:corelib/runtime.js>:1644:7:in `each'", "<internal:corelib/array.rb>:983:1:in `each'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each'", "mspec/runner/mspec.rb:90:12:in `each_file'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each_file'", "mspec/runner/mspec.rb:95:5:in `files'", "mspec/runner/mspec.rb:63:5:in `process'", "tmp/mspec_nodejs.rb:3880:6:in `undefined'", "<internal:corelib/runtime.js>:2805:7:in `<main>'", "tmp/mspec_nodejs.rb:1:1:in `null'", "node:internal/modules/cjs/loader:1105:14:in `Module._compile'", "node:internal/modules/cjs/loader:1159:10:in `Module._extensions..js'", "node:internal/modules/cjs/loader:981:32:in `Module.load'", "node:internal/modules/cjs/loader:822:12:in `Module._load'", "node:internal/modules/run_main:77:12:in `executeUserEntryPoint'", "node:internal/main/run_main_module:17:47:in `undefined'"] to be nil
  fails "Exception#backtrace_locations produces a backtrace for an exception captured using $!" # Expected "<internal:corelib/kernel.rb>" =~ /backtrace_locations_spec/ to be truthy but was nil
  fails "Exception#backtrace_locations returns nil if no backtrace was set" # Expected ["ruby/core/exception/backtrace_locations_spec.rb:10:14:in `instance_exec'", "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `instance_exec'", "mspec/runner/mspec.rb:116:11:in `protect'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `protect'", "mspec/runner/context.rb:176:39:in `$$17'", "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'", "<internal:corelib/enumerable.rb>:27:16:in `$$3'", "<internal:corelib/runtime.js>:1644:7:in `each'", "<internal:corelib/array.rb>:983:1:in `each'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each'", "<internal:corelib/enumerable.rb>:26:7:in `Enumerable_all$ques$1'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `all?'", "mspec/runner/context.rb:176:18:in `protect'", "mspec/runner/context.rb:212:26:in `$$21'", "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'", "mspec/runner/mspec.rb:284:7:in `repeat'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `repeat'", "mspec/runner/context.rb:204:16:in `$$20'", "<internal:corelib/runtime.js>:1644:7:in `each'", "<internal:corelib/array.rb>:983:1:in `each'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each'", "mspec/runner/context.rb:203:18:in `process'", "mspec/runner/mspec.rb:55:10:in `describe'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `describe'", "mspec/runner/object.rb:11:10:in `describe'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `describe'", "ruby/core/exception/backtrace_locations_spec.rb:4:1:in `Opal.modules.ruby/core/exception/backtrace_locations_spec'", "<internal:corelib/runtime.js>:2692:7:in `Opal.load_normalized'", "<internal:corelib/runtime.js>:2721:5:in `load'", "<internal:corelib/kernel.rb>:535:6:in `load'", "mspec/runner/mspec.rb:99:42:in `instance_exec'", "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `instance_exec'", "mspec/runner/mspec.rb:116:11:in `protect'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `protect'", "mspec/runner/mspec.rb:99:7:in `$$1'", "<internal:corelib/runtime.js>:1644:7:in `each'", "<internal:corelib/array.rb>:983:1:in `each'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each'", "mspec/runner/mspec.rb:90:12:in `each_file'", "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'", "<internal:corelib/runtime.js>:1866:5:in `each_file'", "mspec/runner/mspec.rb:95:5:in `files'", "mspec/runner/mspec.rb:63:5:in `process'", "tmp/mspec_nodejs.rb:3880:6:in `undefined'", "<internal:corelib/runtime.js>:2805:7:in `<main>'", "tmp/mspec_nodejs.rb:1:1:in `null'", "node:internal/modules/cjs/loader:1105:14:in `Module._compile'", "node:internal/modules/cjs/loader:1159:10:in `Module._extensions..js'", "node:internal/modules/cjs/loader:981:32:in `Module.load'", "node:internal/modules/cjs/loader:822:12:in `Module._load'", "node:internal/modules/run_main:77:12:in `executeUserEntryPoint'", "node:internal/main/run_main_module:17:47:in `undefined'"] to be nil
  fails "Exception#cause is set for internal errors caused by user errors" # Expected ZeroDivisionError but no exception was raised (Infinity was returned)
  fails "Exception#cause is set for user errors caused by internal errors" # Expected RuntimeError but no exception was raised (Infinity was returned)
  fails "Exception#detailed_message accepts highlight keyword argument and adds escape control sequences" # NoMethodError: undefined method `detailed_message' for #<RuntimeError: new error>
  fails "Exception#detailed_message allows and ignores other keyword arguments" # NoMethodError: undefined method `detailed_message' for #<RuntimeError: new error>
  fails "Exception#detailed_message returns 'unhandled exception' for an instance of RuntimeError with empty message" # NoMethodError: undefined method `detailed_message' for RuntimeError
  fails "Exception#detailed_message returns a generated class name for an instance of RuntimeError anonymous subclass with empty message" # NoMethodError: undefined method `detailed_message' for #<Class:0x4b72c>
  fails "Exception#detailed_message returns decorated message" # NoMethodError: undefined method `detailed_message' for #<RuntimeError: new error>
  fails "Exception#detailed_message returns just a message if exception class is anonymous" # NoMethodError: undefined method `detailed_message' for #<#<Class:0x4b742>: message>
  fails "Exception#detailed_message returns just class name for an instance of RuntimeError sublass with empty message" # NoMethodError: undefined method `detailed_message' for DetailedMessageSpec::C
  fails "Exception#exception captures an exception into $!" # Expected "<internal:corelib/kernel.rb>:609:37:in `raise'" =~ /exception_spec/ to be truthy but was nil
  fails "Exception#full_message highlights the entire message when the message contains multiple lines" # Expected  "<internal:corelib/kernel.rb>:612:37:in `raise': \e[1mfirst line ".start_with? "ruby/core/exception/full_message_spec.rb:62:in `" to be truthy but was false
  fails "Exception#full_message passes all its own keyword arguments to #detailed_message" # NoMethodError: undefined method `to_tty?' for Exception
  fails "Exception#full_message relies on #detailed_message" # Expected  "ruby/core/exception/full_message_spec.rb:109:23:in `instance_exec': \e[1mnew error (\e[1;4mRuntimeError\e[m\e[1m)\e[m " =~ /DETAILED MESSAGE/ to be truthy but was nil
  fails "Exception#full_message shows the caller if the exception has no backtrace" # Expected ["ruby/core/exception/full_message_spec.rb:42:21:in `instance_exec'",  "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `instance_exec'",  "mspec/runner/mspec.rb:116:11:in `protect'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `protect'",  "mspec/runner/context.rb:176:39:in `$$17'",  "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'",  "<internal:corelib/enumerable.rb>:27:16:in `$$3'",  "<internal:corelib/runtime.js>:1644:7:in `each'",  "<internal:corelib/array.rb>:983:1:in `each'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each'",  "<internal:corelib/enumerable.rb>:26:7:in `Enumerable_all$ques$1'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `all?'",  "mspec/runner/context.rb:176:18:in `protect'",  "mspec/runner/context.rb:212:26:in `$$21'",  "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'",  "mspec/runner/mspec.rb:284:7:in `repeat'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `repeat'",  "mspec/runner/context.rb:204:16:in `$$20'",  "<internal:corelib/runtime.js>:1644:7:in `each'",  "<internal:corelib/array.rb>:983:1:in `each'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each'",  "mspec/runner/context.rb:203:18:in `process'",  "mspec/runner/mspec.rb:55:10:in `describe'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `describe'",  "mspec/runner/object.rb:11:10:in `describe'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `describe'",  "ruby/core/exception/full_message_spec.rb:3:1:in `Opal.modules.ruby/core/exception/full_message_spec'",  "<internal:corelib/runtime.js>:2692:7:in `Opal.load_normalized'",  "<internal:corelib/runtime.js>:2721:5:in `load'",  "<internal:corelib/kernel.rb>:535:6:in `load'",  "mspec/runner/mspec.rb:99:42:in `instance_exec'",  "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `instance_exec'",  "mspec/runner/mspec.rb:116:11:in `protect'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `protect'",  "mspec/runner/mspec.rb:99:7:in `$$1'",  "<internal:corelib/runtime.js>:1644:7:in `each'",  "<internal:corelib/array.rb>:983:1:in `each'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each'",  "mspec/runner/mspec.rb:90:12:in `each_file'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each_file'",  "mspec/runner/mspec.rb:95:5:in `files'",  "mspec/runner/mspec.rb:63:5:in `process'",  "tmp/mspec_nodejs.rb:3880:6:in `undefined'",  "<internal:corelib/runtime.js>:2805:7:in `<main>'",  "tmp/mspec_nodejs.rb:1:1:in `null'",  "node:internal/modules/cjs/loader:1105:14:in `Module._compile'",  "node:internal/modules/cjs/loader:1159:10:in `Module._extensions..js'",  "node:internal/modules/cjs/loader:981:32:in `Module.load'",  "node:internal/modules/cjs/loader:822:12:in `Module._load'",  "node:internal/modules/run_main:77:12:in `executeUserEntryPoint'",  "node:internal/main/run_main_module:17:47:in `undefined'"] == nil to be truthy but was false
  fails "Exception#full_message shows the exception class at the end of the first line of the message when the message contains multiple lines" # Expected  "<internal:corelib/kernel.rb>:612:37:in `raise': first line ".start_with? "ruby/core/exception/full_message_spec.rb:51:in `" to be truthy but was false
  fails "Exception#full_message supports :highlight option and adds escape sequences to highlight some strings" # Expected "ruby/core/exception/full_message_spec.rb:16:21:in `instance_exec': \e[1mSome runtime error (\e[1;4mRuntimeError\e[m\e[1m)\e[m".end_with?  "\e[1mSome runtime error (\e[1;4mRuntimeError\e[m\e[1m)\e[m " to be truthy but was false
  fails "Exception#full_message supports :order option and places the error message and the backtrace at the top or the bottom" # Expected  "a.rb:1: Some runtime error (RuntimeError) \tfrom b.rb:2 " =~ /a.rb:1.*b.rb:2/m to be truthy but was nil
  fails "Exception#set_backtrace raises a TypeError when passed a Symbol" # Expected TypeError but no exception was raised ("unhappy" was returned)
  fails "Exception#set_backtrace raises a TypeError when the Array contains a Symbol" # Expected TypeError but no exception was raised (["String", "unhappy"] was returned)
  fails "Exception#to_s calls #to_s on the message" # Mock 'message' expected to receive to_s("any_args") exactly 1 times but received it 2 times
  fails "Interrupt is raised on the main Thread by the default SIGINT handler" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x52262>
  fails "Interrupt.new returns an instance of interrupt with no message given" # NoMethodError: undefined method `signo' for #<Interrupt: Interrupt>
  fails "Interrupt.new takes an optional message argument" # NoMethodError: undefined method `signo' for #<Interrupt: message>
  fails "KeyError accepts :receiver and :key options" # ArgumentError: no receiver is available
  fails "NameError#dup copies the name and receiver" # NoMethodError: undefined method `receiver' for #<NoMethodError: undefined method `foo' for #<MSpecEnv:0x39754>>
  fails "NameError#name returns a class variable name as a symbol" # Expected nil == "@@doesnt_exist" to be truthy but was false
  fails "NameError#receiver returns a class when an undefined class variable is called in a subclass' namespace" # NoMethodError: undefined method `receiver' for #<NameError: uninitialized class variable @@doesnt_exist in NameErrorSpecs::ReceiverClass>
  fails "NameError#receiver returns a class when an undefined constant is called" # NoMethodError: undefined method `receiver' for #<NameError: uninitialized constant NameErrorSpecs::ReceiverClass::DoesntExist>
  fails "NameError#receiver returns the Object class when an undefined class variable is called" # NoMethodError: undefined method `receiver' for #<NameError: uninitialized class variable @@doesnt_exist in >
  fails "NameError#receiver returns the Object class when an undefined constant is called without namespace" # NoMethodError: undefined method `receiver' for #<NameError: uninitialized constant DoesntExist>
  fails "NameError#receiver returns the object that raised the exception" # NoMethodError: undefined method `receiver' for #<NoMethodError: undefined method `doesnt_exist' for #<Object:0x1a114>>
  fails "NameError#receiver returns the receiver when raised from #class_variable_get" # NoMethodError: undefined method `receiver' for #<NameError: `invalid_cvar_name' is not allowed as a class variable name>
  fails "NameError#receiver returns the receiver when raised from #instance_variable_get" # NoMethodError: undefined method `receiver' for #<NameError: 'invalid_ivar_name' is not allowed as an instance variable name>
  fails "NameError#to_s raises its own message for an undefined variable" # Expected "undefined method `not_defined' for #<MSpecEnv:0xb0b34>" =~ /undefined local variable or method `not_defined'/ to be truthy but was nil
  fails "NameError.new accepts a :receiver keyword argument" # ArgumentError: [NameError#initialize] wrong number of arguments (given 3, expected -2)
  fails "NoMethodError#dup copies the name, arguments and receiver" # NoMethodError: undefined method `receiver' for #<NoMethodError: undefined method `foo' for #<Object:0x11274>>
  fails "NoMethodError.new accepts a :receiver keyword argument" # NoMethodError: undefined method `receiver' for #<NoMethodError: msg>
  fails "SignalException can be rescued" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x52502>
  fails "SignalException cannot be trapped with Signal.trap" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x52502>
  fails "SignalException runs after at_exit" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x52502>
  fails "SignalException self-signals for USR1" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x52502>
  fails "SignalException#signm returns the signal name" # Expected SignalException but got: NoMethodError (undefined method `kill' for Process)
  fails "SignalException#signo returns the signal number" # Expected SignalException but got: NoMethodError (undefined method `kill' for Process)
  fails "SignalException.new raises an exception for an optional argument with a signal name" # Expected ArgumentError but no exception was raised (#<SignalException: INT> was returned)
  fails "SignalException.new raises an exception with an invalid first argument type" # Expected ArgumentError but no exception was raised (#<SignalException: #<Object:0x52564>> was returned)
  fails "SignalException.new raises an exception with an invalid signal name" # Expected ArgumentError but no exception was raised (#<SignalException: NONEXISTENT> was returned)
  fails "SignalException.new raises an exception with an invalid signal number" # Expected ArgumentError but no exception was raised (#<SignalException: 100000> was returned)
  fails "SignalException.new takes a signal name with SIG prefix as the first argument" # NoMethodError: undefined method `signo' for #<SignalException: SIGINT>
  fails "SignalException.new takes a signal name without SIG prefix as the first argument" # NoMethodError: undefined method `signo' for #<SignalException: INT>
  fails "SignalException.new takes a signal number as the first argument" # NoMethodError: undefined method `list' for Signal
  fails "SignalException.new takes a signal symbol with SIG prefix as the first argument" # NoMethodError: undefined method `signo' for #<SignalException: SIGINT>
  fails "SignalException.new takes a signal symbol without SIG prefix as the first argument" # NoMethodError: undefined method `signo' for #<SignalException: INT>
  fails "SignalException.new takes an optional message argument with a signal number" # NoMethodError: undefined method `list' for Signal
  fails "StopIteration#result returns the method-returned-object from an Enumerator" # Expected nil to be identical to "method_returned"
  fails "SystemCallError#backtrace is nil if not raised" # Expected ["ruby/core/exception/system_call_error_spec.rb:141:20:in `instance_exec'",  "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `instance_exec'",  "mspec/runner/mspec.rb:116:11:in `protect'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `protect'",  "mspec/runner/context.rb:176:39:in `$$17'",  "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'",  "<internal:corelib/enumerable.rb>:27:16:in `$$3'",  "<internal:corelib/runtime.js>:1644:7:in `each'",  "<internal:corelib/array.rb>:983:1:in `each'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each'",  "<internal:corelib/enumerable.rb>:26:7:in `Enumerable_all$ques$1'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `all?'",  "mspec/runner/context.rb:176:18:in `protect'",  "mspec/runner/context.rb:212:26:in `$$21'",  "<internal:corelib/runtime.js>:1667:5:in `Opal.yieldX'",  "mspec/runner/mspec.rb:284:7:in `repeat'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `repeat'",  "mspec/runner/context.rb:204:16:in `$$20'",  "<internal:corelib/runtime.js>:1644:7:in `each'",  "<internal:corelib/array.rb>:983:1:in `each'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each'",  "mspec/runner/context.rb:203:18:in `process'",  "mspec/runner/mspec.rb:55:10:in `describe'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `describe'",  "mspec/runner/object.rb:11:10:in `describe'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `describe'",  "ruby/core/exception/system_call_error_spec.rb:139:1:in `Opal.modules.ruby/core/exception/system_call_error_spec'",  "<internal:corelib/runtime.js>:2692:7:in `Opal.load_normalized'",  "<internal:corelib/runtime.js>:2721:5:in `load'",  "<internal:corelib/kernel.rb>:535:6:in `load'",  "mspec/runner/mspec.rb:99:42:in `instance_exec'",  "<internal:corelib/basic_object.rb>:125:1:in `instance_exec'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `instance_exec'",  "mspec/runner/mspec.rb:116:11:in `protect'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `protect'",  "mspec/runner/mspec.rb:99:7:in `$$1'",  "<internal:corelib/runtime.js>:1644:7:in `each'",  "<internal:corelib/array.rb>:983:1:in `each'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each'",  "mspec/runner/mspec.rb:90:12:in `each_file'",  "<internal:corelib/runtime.js>:1878:5:in `Opal.send2'",  "<internal:corelib/runtime.js>:1866:5:in `each_file'",  "mspec/runner/mspec.rb:95:5:in `files'",  "mspec/runner/mspec.rb:63:5:in `process'",  "tmp/mspec_nodejs.rb:3880:6:in `undefined'",  "<internal:corelib/runtime.js>:2805:7:in `<main>'",  "tmp/mspec_nodejs.rb:1:1:in `null'",  "node:internal/modules/cjs/loader:1105:14:in `Module._compile'",  "node:internal/modules/cjs/loader:1159:10:in `Module._extensions..js'",  "node:internal/modules/cjs/loader:981:32:in `Module.load'",  "node:internal/modules/cjs/loader:822:12:in `Module._load'",  "node:internal/modules/run_main:77:12:in `executeUserEntryPoint'",  "node:internal/main/run_main_module:17:47:in `undefined'"] == nil to be truthy but was false
  fails "SystemCallError#dup copies the errno" # Expected nil == 42 to be truthy but was false
  fails "SystemCallError#errno returns the errno given as optional argument to new" # Expected nil == -1048576 to be truthy but was false
  fails "SystemCallError#message returns the default message when no message is given" # Expected "268435456" =~ /Unknown error/i to be truthy but was nil
  fails "SystemCallError.=== returns false if errnos different" # NoMethodError: undefined method `+' for Errno
  fails "SystemCallError.=== returns true if errnos same" # Expected false == true to be truthy but was false
  fails "SystemCallError.new accepts an optional custom message preceding the errno" # Expected #<SystemCallError: custom message> (SystemCallError) to be an instance of Errno::EINVAL
  fails "SystemCallError.new accepts an optional third argument specifying the location" # Expected #<SystemCallError: custom message> (SystemCallError) to be an instance of Errno::EINVAL
  fails "SystemCallError.new accepts single Integer argument as errno" # Expected nil == -16777216 to be truthy but was false
  fails "SystemCallError.new coerces location if it is not a String" # Expected "foo" =~ /@ not_a_string - foo/ to be truthy but was nil
  fails "SystemCallError.new constructs the appropriate Errno class" # Expected #<SystemCallError: Errno> (SystemCallError) to be an instance of Errno::EINVAL
  fails "SystemCallError.new converts to Integer if errno is a Complex convertible to Integer" # Expected #<SystemCallError: foo> == #<SystemCallError: foo> to be truthy but was false
  fails "SystemCallError.new converts to Integer if errno is a Float" # Expected #<SystemCallError: foo> == #<SystemCallError: foo> to be truthy but was false
  fails "SystemCallError.new raises RangeError if errno is a Complex not convertible to Integer" # Expected RangeError (/can't convert/) but no exception was raised (#<SystemCallError: foo> was returned)
  fails "SystemCallError.new raises TypeError if errno is not an Integer" # Expected TypeError (/no implicit conversion of String into Integer/) but no exception was raised (#<SystemCallError: foo> was returned)
  fails "SystemCallError.new raises TypeError if message is not a String" # Expected TypeError (/no implicit conversion of Symbol into String/) but no exception was raised (#<SystemCallError: foo> was returned)
  fails "SystemCallError.new requires at least one argument" # Expected ArgumentError but no exception was raised (#<SystemCallError: SystemCallError> was returned)
  fails "SystemExit #initialize accepts a message only" # NoMethodError: undefined method `status' for #<SystemExit: message>
  fails "SystemExit #initialize accepts a status and message" # NoMethodError: undefined method `status' for #<SystemExit: 42>
  fails "SystemExit #initialize accepts a status only" # NoMethodError: undefined method `status' for #<SystemExit: 42>
  fails "SystemExit #initialize accepts no arguments" # NoMethodError: undefined method `status' for #<SystemExit: SystemExit>
  fails "SystemExit sets the exit status and exits silently when raised when subclassed" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x9fe6a>
  fails "SystemExit sets the exit status and exits silently when raised" # NoMethodError: undefined method `tmp' for #<MSpecEnv:0x9fe6a>
  fails_badly "SystemExit#status returns the exit status"
  fails_badly "SystemExit#success? returns false if the process exited unsuccessfully"
  fails_badly "SystemExit#success? returns true if the process exited successfully"
end
